# Generated by Django 3.0 on 2023-03-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
